version: 2
jobs: 
  review:
    working_directory: ~/microbit-foundation/python-editor
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: python:3.6-jessie
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: apt-get update
    - run: apt-get install jq
    - run: pip install awscli
    - run: ./bin/build
    - run: ./bin/deploy ${CIRCLE_BRANCH}-review
  release:
    working_directory: ~/microbit-foundation/python-editor
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: python:3.6-jessie
    steps:
    - checkout
    - run: git submodule sync
    - run: git submodule update --init
    - run: apt-get update
    - run: apt-get install jq
    - run: pip install awscli
    - run: ./bin/build
    - run: ./bin/deploy $(cat VERSION)


workflows:
  version: 2
  build_deploy:
    jobs:
      - review:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

